server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-db
      username: order_user
      password: order-secret-2026
      authentication-database: order-db
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


product-service:
  url: http://product-service:8082
