map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    resolver 127.0.0.11 valid=30s;
    absolute_redirect off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # WebSocket — order-service
    location /ws/order/ {
        set $order http://order-service:8083;
        proxy_pass $order;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header Origin http://localhost:3002;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # WebSocket — search-service
    location /ws/search/ {
        set $search http://search-service:8086;
        proxy_pass $search;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header Origin http://localhost:3002;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # product-service
    location /sell {
        set $product http://product-service:8082;
        proxy_pass $product;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # search-service
    location /search {
        set $search http://search-service:8086;
        proxy_pass $search;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # order-service
    location /order {
        set $order http://order-service:8083;
        proxy_pass $order;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # member-service
    location /member {
        set $member http://member-service:8081;
        proxy_pass $member;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # point-service
    location /point {
        set $point http://point-service:8084;
        proxy_pass $point;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # payment-service
    location /payment {
        set $payment http://payment-service:8085;
        proxy_pass $payment;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /survey {
        set $product http://product-service:8082;
        proxy_pass $product;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /my {
        set $member http://member-service:8081;
        proxy_pass $member;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /note {
        set $member http://member-service:8081;
        proxy_pass $member;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
