server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      username: product_user
      password: product-secret-2026
      authentication-database: product-db
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: GongGuHaSong.product.event.OrderEvent
        spring.json.use.type.headers: false
